# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=200),
            preserve_default=False,
        ),
    ]
