# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=30),
            preserve_default=False,
        ),
    ]
