# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='firstname', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='lastname', max_length=200),
            preserve_default=False,
        ),
    ]
