# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171113_0254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Donor',
        ),
    ]
