# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171113_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=400)),
                ('elevator_pitch', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_verified_501c3', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('Op', 'Open'), ('Cl', 'Closed'), ('Cr', 'Creating'), ('Ve', 'Verifying')], default='Cr', max_length=2)),
            ],
        ),
    ]
